TRUNCATE TABLE chunk CASCADE;
TRUNCATE TABLE result CASCADE;
TRUNCATE TABLE project CASCADE;
TRUNCATE TABLE file CASCADE;
TRUNCATE TABLE rating CASCADE;
TRUNCATE TABLE criterion CASCADE;
TRUNCATE TABLE "user" CASCADE;