"""Altered user to use email and not username or name

Revision ID: ba7596c6e383
Revises: f95b55dbe61e
Create Date: 2024-09-25 14:50:57.459113

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ba7596c6e383"
down_revision: Union[str, None] = "f95b55dbe61e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sa.String()))
    op.drop_column("user", "username")
    op.drop_column("user", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column("user", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("user", "email")
    # ### end Alembic commands ###
