"""Add dates to rating table

Revision ID: f95b55dbe61e
Revises: 70ce592d9ad5
Create Date: 2024-09-23 12:12:25.654102

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f95b55dbe61e"
down_revision: Union[str, None] = "70ce592d9ad5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rating",
        sa.Column(
            "created_datetime",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "rating",
        sa.Column("updated_datetime", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rating", "updated_datetime")
    op.drop_column("rating", "created_datetime")
    # ### end Alembic commands ###
